export type Role = 'STUDENT' | 'ADMIN';
export type ListingStatus = 'PENDING' | 'ACTIVE' | 'REJECTED' | 'SOLD' | 'INACTIVE' | 'HIDDEN' | 'REMOVED';
export type ComplaintStatus = 'OPEN' | 'IN_REVIEW' | 'RESOLVED' | 'DISMISSED';
export type TransactionStatus = 'PENDING' | 'PAID' | 'CONFIRMED' | 'COMPLETED' | 'CANCELLED';
export type FulfillmentMethod = 'CAMPUS_MEETUP' | 'INSTANT_COURIER';
export type CourierProvider = 'GOSEND' | 'GRABEXPRESS';
export interface User { id: string; email: string; name: string; studentId?: string | null; phone?: string | null; bio?: string | null; avatarUrl?: string | null; role: Role; isVerified?: boolean; isActive?: boolean; balance?: number | string; escrow?: number | string; _count?: Record<string, number>; }
export interface Listing { id: string; title: string; description: string; price: number | string; category: string; type: 'PRODUCT' | 'SERVICE'; images: string[]; status: ListingStatus; condition?: string | null; stock?: number | null; stockLeft?: number | null; fulfillmentMethods: FulfillmentMethod[]; sellerId: string; seller?: Partial<User>; createdAt: string; }
export interface Transaction { id: string; buyerId: string; sellerId: string; status: TransactionStatus; quantity: number; price: number | string; totalPrice: number | string; fulfillmentMethod: FulfillmentMethod; meetupCampus?: string | null; meetupLocation?: string | null; meetupSchedule?: string | null; courierProvider?: CourierProvider | null; deliveryAddress?: string | null; recipientPhone?: string | null; shippingFee: number | string; grandTotal: number | string; trackingNumber?: string | null; handoverCodeExpiresAt?: string | null; handoverVerifiedAt?: string | null; commissionRate: number | string; commissionAmt: number | string; sellerReceives: number | string; isEscrowHeld: boolean; note?: string | null; paidAt?: string | null; confirmedAt?: string | null; completedAt?: string | null; cancelledAt?: string | null; cancelledBy?: 'BUYER' | 'SELLER' | null; cancellationReason?: string | null; createdAt: string; updatedAt?: string; listing: Listing; buyer: Partial<User>; seller: Partial<User>; review?: { rating: number } | null; }
export interface CheckoutOptions { fulfillmentMethods: FulfillmentMethod[]; campuses: string[]; couriers: { provider: CourierProvider; label: string; fee: number; eta: string }[]; }
export interface Message { id: string; chatRoomId: string; senderId: string; content: string; isRead: boolean; createdAt: string; sender?: Partial<User>; }
export interface ChatRoom { id: string; userAId: string; userBId: string; userA: Partial<User>; userB: Partial<User>; unreadCount: number; messages: Message[]; updatedAt?: string; createdAt: string; }
export interface Complaint { id: string; reporterId: string; targetType: 'USER' | 'LISTING'; targetId: string; reason: string; description?: string | null; status: ComplaintStatus; adminNote?: string | null; createdAt: string; updatedAt: string; reporter?: Partial<User>; targetListing?: Listing | null; targetUser?: Partial<User> | null; }
export interface ApiEnvelope<T> { success: boolean; data: T; message?: string; }
export interface Page<T> { data: T[]; total: number; page: number; limit: number; totalPages: number; }
