import Ionicons from '@expo/vector-icons/Ionicons';
import { useMemo, useState } from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { useQuery } from '@tanstack/react-query';
import { router } from 'expo-router';
import { Card, Empty, ErrorState, Field, Loader, Screen, Title } from '@/components/ui';
import { endpoints, errorMessage } from '@/lib/api';
import { colors, radius } from '@/constants/theme';
import { useAuth } from '@/store/auth';

export default function ChatsScreen(){const user=useAuth(s=>s.user);const[search,setSearch]=useState('');const query=useQuery({queryKey:['rooms'],queryFn:endpoints.rooms,refetchInterval:15000});const rooms=useMemo(()=>query.data?.filter(room=>{const other=room.userAId===user?.id?room.userB:room.userA;return(other.name||'').toLowerCase().includes(search.toLowerCase())})||[],[query.data,search,user?.id]);return <Screen><Title eyebrow="PESAN BMArket" subtitle="Tanyakan kondisi, sepakati lokasi, dan simpan detail transaksi.">Pesan</Title><View style={s.safety}><View style={s.safetyIcon}><Ionicons name="shield-checkmark-outline" size={21} color={colors.success}/></View><View style={s.safetyBody}><Text style={s.safetyTitle}>Jaga percakapan tetap di BMarket</Text><Text style={s.safetyText}>Hindari membagikan OTP atau data pribadi kepada pengguna lain.</Text></View><Ionicons name="close-outline" size={19} color={colors.muted}/></View><View style={s.toolbar}><View style={s.search}><Field value={search} onChangeText={setSearch} icon="search-outline" placeholder="Cari nama pengguna..."/></View><View style={s.unread}><View style={s.unreadDot}/><Text style={s.unreadText}>{query.data?.reduce((sum,room)=>sum+(room.unreadCount||0),0)||0} belum dibaca</Text></View></View>{query.isLoading?<Loader/>:query.isError?<ErrorState message={errorMessage(query.error)} retry={()=>query.refetch()}/>:!rooms.length?<Empty title={search?'Percakapan tidak ditemukan':'Belum ada percakapan'} message={search?'Coba nama pengguna yang lain.':'Mulai percakapan dari halaman detail barang atau jasa.'} icon="chatbubble-ellipses-outline"/>:<Card style={s.list}>{rooms.map((room,index)=>{const other=room.userAId===user?.id?room.userB:room.userA;const message=room.messages?.[0];return <Pressable key={room.id} onPress={()=>router.push({pathname:'/(student)/chat/[id]',params:{id:room.id,name:other.name||'Chat'}})} style={({pressed})=>[s.row,index===rooms.length-1&&s.rowLast,pressed&&{opacity:.65}]}><View style={s.avatar}><Text style={s.avatarText}>{other.name?.[0]?.toUpperCase()||'?'}</Text><View style={s.online}/></View><View style={s.body}><View style={s.nameRow}><Text style={s.name}>{other.name||'Binusian'}</Text><Text style={s.time}>{message?'Baru saja':''}</Text></View><Text numberOfLines={1} style={s.preview}>{message?.content||'Belum ada pesan'}</Text></View>{room.unreadCount?<Text style={s.count}>{room.unreadCount}</Text>:<Ionicons name="chevron-forward" size={17} color={colors.borderStrong}/>}</Pressable>})}</Card>}</Screen>}

const s=StyleSheet.create({safety:{minHeight:84,borderRadius:14,backgroundColor:colors.successSoft,borderWidth:1,borderColor:'#CDEBDD',flexDirection:'row',alignItems:'center',gap:14,paddingHorizontal:18},safetyIcon:{width:46,height:46,borderRadius:12,backgroundColor:colors.surface,alignItems:'center',justifyContent:'center'},safetyBody:{flex:1},safetyTitle:{fontFamily:'PoppinsSemiBold',fontSize:14,color:colors.text},safetyText:{fontFamily:'PoppinsRegular',fontSize:11,lineHeight:18,color:colors.muted},toolbar:{flexDirection:'row',alignItems:'center',gap:16,flexWrap:'wrap'},search:{flex:1,minWidth:260,maxWidth:620},unread:{minHeight:38,flexDirection:'row',alignItems:'center',gap:7,paddingHorizontal:13,paddingVertical:8,borderRadius:radius.pill,backgroundColor:colors.surface,borderWidth:1,borderColor:colors.border},unreadDot:{width:7,height:7,borderRadius:4,backgroundColor:colors.primary},unreadText:{fontFamily:'PoppinsMedium',fontSize:11,color:colors.textSoft},list:{paddingVertical:5,gap:0},row:{minHeight:90,flexDirection:'row',alignItems:'center',gap:15,paddingVertical:14,borderBottomWidth:1,borderBottomColor:colors.border},rowLast:{borderBottomWidth:0},avatar:{width:54,height:54,borderRadius:15,backgroundColor:colors.primarySoft,alignItems:'center',justifyContent:'center'},avatarText:{fontFamily:'PoppinsBold',fontSize:18,color:colors.primary},online:{position:'absolute',right:-1,bottom:-1,width:12,height:12,borderRadius:6,backgroundColor:colors.success,borderWidth:2,borderColor:colors.surface},body:{flex:1},nameRow:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:12},name:{fontFamily:'PoppinsSemiBold',fontSize:14,color:colors.text},time:{fontFamily:'PoppinsRegular',fontSize:10,color:colors.muted},preview:{fontFamily:'PoppinsRegular',fontSize:12,lineHeight:19,color:colors.muted,marginTop:4},count:{minWidth:26,height:26,borderRadius:13,overflow:'hidden',backgroundColor:colors.primary,color:colors.white,textAlign:'center',paddingTop:4,fontFamily:'PoppinsBold',fontSize:10}});
